"use client";

import { useState } from "react";
import { Bot, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { SUGGESTED_PROMPTS, answerSuggestedPrompt } from "@/lib/services/investigatorCopilot";
import type { InvestigatorScenario } from "@/lib/services/investigatorScenario";
import { cn } from "@/lib/utils";

interface ThreadMessage {
  id: string;
  role: "analyst" | "copilot";
  text: string;
  citations?: string[];
  isNotConnected?: boolean;
}

/**
 * No language model is connected here -- there isn't one anywhere in this
 * stack. Suggested prompts map to a fixed template filled with real,
 * already-computed evidence (see lib/services/investigatorCopilot.ts); a
 * free-text question gets an honest "not connected" reply, never an
 * invented answer. This mirrors the same pattern
 * components/investigation/AssessmentServiceNotConnected.tsx already uses
 * for a genuinely unconnected service.
 */
export function CopilotPanel({ scenario, className }: { scenario: InvestigatorScenario; className?: string }) {
  const [thread, setThread] = useState<ThreadMessage[]>([]);
  const [draft, setDraft] = useState("");

  function askSuggested(promptId: string, question: string) {
    const answer = answerSuggestedPrompt(promptId, scenario);
    setThread((prev) => [
      ...prev,
      { id: `${Date.now()}-q`, role: "analyst", text: question },
      answer
        ? { id: `${Date.now()}-a`, role: "copilot", text: answer.text, citations: answer.citations }
        : { id: `${Date.now()}-a`, role: "copilot", text: "No case is open, so there's no evidence to answer from.", isNotConnected: true },
    ]);
  }

  function submitCustom(event: React.FormEvent) {
    event.preventDefault();
    const question = draft.trim();
    if (!question) return;
    setThread((prev) => [
      ...prev,
      { id: `${Date.now()}-q`, role: "analyst", text: question },
      {
        id: `${Date.now()}-a`,
        role: "copilot",
        isNotConnected: true,
        text: "AI Copilot is not connected in this build — there's no language model behind this panel. Try one of the suggested prompts above for a real, evidence-based answer instead.",
      },
    ]);
    setDraft("");
  }

  return (
    <div className={cn("flex min-h-0 flex-col border-l border-border bg-panel-2", className)}>
      <div className="flex shrink-0 items-center justify-between gap-2 border-b border-border px-3 py-2">
        <p className="flex items-center gap-1.5 text-xs font-semibold tracking-wide text-foreground uppercase">
          <Bot className="size-3.5" aria-hidden="true" />
          AI Copilot
        </p>
        <span className="rounded border border-status-info/30 bg-status-info/10 px-1.5 py-0.5 text-[0.65rem] text-status-info">
          Simulated — not connected
        </span>
      </div>

      <ScrollArea className="min-h-0 flex-1">
        <div className="flex flex-col gap-2 p-3">
          {thread.length === 0 && (
            <p className="text-xs text-muted-foreground">
              Ask a suggested question below — answers are templated from this case&apos;s real evidence, not generated by a
              live model.
            </p>
          )}
          {thread.map((message) => (
            <div
              key={message.id}
              className={cn(
                "rounded-md border p-2 text-xs",
                message.role === "analyst" ? "border-border bg-panel" : "border-status-info/30 bg-status-info/5",
              )}
            >
              <p className={message.isNotConnected ? "text-muted-foreground italic" : "text-foreground"}>{message.text}</p>
              {message.citations && message.citations.length > 0 && (
                <ul className="mt-1.5 flex flex-wrap gap-1">
                  {message.citations.map((citation) => (
                    <li key={citation} className="rounded border border-border px-1.5 py-0.5 font-data text-[0.6rem] text-muted-foreground">
                      {citation}
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </div>
      </ScrollArea>

      <div className="shrink-0 border-t border-border p-2">
        <p className="mb-1.5 text-[0.65rem] font-semibold tracking-wide text-muted-foreground uppercase">Suggested prompts</p>
        <div className="mb-2 flex flex-wrap gap-1">
          {SUGGESTED_PROMPTS.map((prompt) => (
            <button
              key={prompt.id}
              type="button"
              onClick={() => askSuggested(prompt.id, prompt.question)}
              className="rounded border border-border px-2 py-1 text-[0.7rem] text-muted-foreground hover:border-border-strong hover:text-foreground"
            >
              {prompt.question}
            </button>
          ))}
        </div>
        <form onSubmit={submitCustom} className="flex gap-1.5">
          <Input
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            placeholder="Ask a custom question…"
            className="h-8 text-xs"
            aria-label="Ask the AI Copilot a custom question"
          />
          <Button type="submit" size="icon-sm" variant="outline" aria-label="Send">
            <Send className="size-3.5" />
          </Button>
        </form>
      </div>
    </div>
  );
}
